### ISSUE TITLE
JQ-10/ Create the Recruit Page

### ISSUE THREAD

**Issue by Adissuu** [Adissuu/JobQuest#10]
As a user, if I am a recruiter, I want to be able to see the list of potential employees.

Note: We want to create a ux similar to Linkedin's "Jobs" page.

**Comment by TitiMMM** [comment]
Recruits page was created with basic functionalities. Further work on the design of the pages and implementation with backend will happen in the future.

**Comment by hisham-kitaz** [comment]
Story points allocated to this task : 3.
