### ISSUE TITLE
JQ-21/ <User Story - Switching to dark mode>

### ISSUE THREAD

**Issue by hisham-kitaz** [Adissuu/JobQuest#31]
As an engineer, I propose the applicant be able to view the webpage in dark mode and be able to toggle between dark and 
Tasks:
1. As a user I want to be able to click on a button to switch between dark and light modes. 3 story points\
Story Points: 3.
Explanation of Story Points:
We have allocated 3 story points to this user story as it involves a small amount of work to design and develop the UI.

**Comment by Adissuu** [comment]
Done!
