### ISSUE TITLE
JQ-26/ <AT2.3 - Password Encryption>

### ISSUE THREAD

**Issue by hisham-kitaz** [Adissuu/JobQuest#38]
This acceptance test is for #37 

User acceptance flow:
       1. User Creates their own password and clicks sign up.
       2. User Has his password encrypted.

### See the TestCase form below:
|**Tested Requirement**|_Password Encryption_|
|**Quick Description**|_The user Signs up by creating their password and has their password encrypted_|
|**Prerequisite**|_Database for storage and backed for receiving encrypted passwords_|
|**Input**|_Password as a string_|
|**Expected output**|_Password Encryption success_|
|**Observed output**|_Password Encryption success_|
|**Verdict**|-----|
|**Comments**|Test under progress|

**Comment by Adissuu** [comment]
Feature implemented
