### ISSUE TITLE
JQ-9/Jobs-Page

### ISSUE THREAD

**Issue by dolphinz0** [Adissuu/JobQuest#9]
As a user, I should be able to search for jobs and see a list of all jobs

**Comment by dolphinz0** [comment]
Tasks:
-create default job list page that shows all jobs
-create second job page so when you click on a job from the list it shows the list on the left and details of the job on the right
-create a third job page that shows only the description of the selected job

**Comment by hisham-kitaz** [comment]
Story points allocated to this task is : 5.
